# Generated by Django 3.0.4 on 2020-03-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
